---
title: Montaque Reynolds, Phd
subtitle: Cover Letter
---
I am a recent PhD in philosophy from Saint Louis University. My work has been in philosophy of mind, cognitive science, and moral psychology where I focus on questions regarding the formation of human agency and personhood. I defended my PhD dissertation on moral epistemology and narratives. I attribute my philosophical pedagogy to my dissertation advisor Helen De Cruz, and her work on fiction and philosophy which played an insurmountable role in my philosophical training. In addition my co-advisor Dan Haybron who’s work in value theory and happiness was a large influence on my teaching and research, as well as Eleonore Stump whose work on Thomistic virtues have been a large influence on my understanding of the importance of narrative. In my academic work, I focus broadly on narratives themselves, and what narratives can do for human moral knowledge and understanding.

I have taught undergraduate courses in Ethics, Critical Thinking, introduction to philosophy, and Self and Reality, philosophy of law, aesthetics, and philosophy of mind. In the spring of 2027 I will be teaching my first ever course in personhood and identity where I will focus on an account of social identity grounded in narrative knowledge of one’s self. As part of a larger project tying together sentiment analysis and moral foundations theories, I have also taught graduate level workshops in sentiment analysis, R and quanteda. This project attempted to tie together social epistemology and Aristotelian virtue ethics through a focus on public narratives. I have also designed and delivered several custom asynchronous Philosophy-Digital Humanities courses, where I integrated teaching methods relying on technology to enhance student engagement and critical thinking skills to about 80 students. This summer, I taught an asynchronous introduction to philosophy course to 10 students. This course was based on David Chalmers’ Reality+ and in it, I used the open world video game Elite Dangerous to explore Dave Chalmers’ and Andy Clark’s extended cognition thesis, as well as explore concepts of meaning in virtual environments.

I believe that for a concept to be memorable, it must hold intrinsic value for the student. In my courses, I leverage this fact, providing opportunities for my students to learn from the material that I carefully and thoughtfully curate, and conversations about the material. As such, I push my students to reflect on storytelling and personal engagement. In my student evaluations, my students have noted that they often find the course material and discussions with each other memorable. 
In evaluations, students have often reflected that my approach helps them to see philosophical questions as central to a meaningful life.

Based on my experiences in the digital humanities, I use artifacts from popular culture, songs, plays, video games, etc., in my assignments to motivate students to apply their experiences outside of the classroom to the course material. Which promotes personal engagement with course materials that in turn prompts the student to pursue philosophical insight for its own benefit. This  approach is interdisciplinary, and blends philosophical concepts with digital tools, and focuses on a dynamic learning environment for diverse student groups. 
In addition, I have implemented adaptive learning strategies such as D&D campaigns, tailoring course content to individual student needs, resulting in mixed results.

I also work towards developing a forward-thinking curriculum that bridges traditional philosophical inquiry with contemporary digital literacy. 
This prepares students for an evolving academic landscape that requires an increasing familiarity with digital and computational technologies. With the help of members of MIHLab.org, I was able to create a turn-based dialogue game in Unity. I introduced this game to my students as a study tool. In it, the students would enter the video game where they would be confronted with questions and prompts from fictional figures based on our readings.

My most recent pedagogical projects look to incorporate game play footage and game play as a form of philosophical thought experiment into course discussions.
I am currently a member of the Saint Louis Digital Humanities Network. This is a group of educators in the Saint Louis area that are committed to exploring ways and implications of expanding use of technology for pedagogical purposes. Given that my philosophical interests are motivated by questions about our social environments, these new modes of social interaction are of great interest. With this in mind, I created the Moral Imagination and Hope Laboratory. At MIHLab, we design philosophy thought experiments using Mass Multiplayer Online / Open World video-games (Pilot, fall 2025) as well as create interactive technologies such as video games and curricula. Together with some students from our weekly LO-Phi sessions at Stetson, a weekly hangout with students interested in philosophy, we are crafting and deploying LLM agents into minecraft for various experiments. I hope to collectively explore implications for conducting our lives in digitally represented social environments by using philosophical reflection to better understand how online communities can be used as a social learning environment. It is our hope that we can use emerging technologies to create lasting communities of critical thinkers and civic-minded future generations.

I am excited about the opportunity to contribute to a learning environment that seeks to engage the student population in meaningful philosophical discourse and prepare them for a changing world. My interdisciplinary experience, and philosophical rigor combined with innovative pedagogical methods will be a terrific addition to your department. I would welcome the opportunity to discuss my qualifications and the needs of your department further. Thank you for your time, and for your thoughtful consideration.